#
#  Copyright 2015 VMware, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
---
- name: Sync Host Preparation
  command: cp "{{ instv_xml }}" "{{ item }}"
  with_items:
    - "{{ nsx_tmp }}/{{ vio_cluster_edge_id }}.xml"
    - "{{ nsx_tmp }}/{{ vio_cluster_compute_id }}.xml"

- name: Adding Cluster Object IDs
  xml:
    file: "{{ item.file_name }}"
    xpath: /nwFabricFeatureConfig/resourceConfig/resourceId
    value: "{{ item.cluster_id }}"
  with_items:
    - { file_name: "{{ nsx_tmp }}/{{ vio_cluster_edge_id }}.xml", cluster_id: "{{ vio_cluster_edge_id }}" }
    - { file_name: "{{ nsx_tmp }}/{{ vio_cluster_compute_id }}.xml", cluster_id: "{{ vio_cluster_compute_id }}" }

- name: Sync Network Virtualization Components for Clusters
  uri:
    url: "{{ nsx_sync }}"
    method: POST
    user: "{{ nsx_user }}"
    password: "{{ nsx_password }}"
    body: "{{ lookup('file', nsx_tmp + '/' + item) }}"
    force_basic_auth: yes
    HEADER_Content-Type: "{{ nsx_header }}"
    validate_certs: no
    return_content: yes
  with_items:
    - "{{ vio_cluster_edge_id }}.xml"
    - "{{ vio_cluster_compute_id }}.xml"
  register: instvirt_syncup

- name: Remove files
  file: path="{{ item }}" state=absent
  with_items:
    - "{{ nsx_tmp }}/{{ vio_cluster_edge_id }}.xml"
    - "{{ nsx_tmp }}/{{ vio_cluster_compute_id }}.xml"

