---
- include: prep.yml
- include: getids.yml
- include: vcinfo_a.yml
- include: nsxsys.yml
- include: inst_virt.yml
- include: create_contrl.yml
- include: contrl_deploy_status.yml
- include: loop_check.yml
- include: loop_checkb.yml
- include: seg.yml
- include: vxlan_b.yml
- include: vxlan_c.yml
- include: vdnscope.yml
- include: cleanup.yml
