---
- name: Prep 
  wait_for: timeout=5

- name: vxlan compute cluster xml
  command: cp "{{ vxlanb_xml }}" "{{ vxlanb_tmp }}"

- name: vxlan parent elements xml
  xml:
    file: "{{ vxlanb_tmp }}"
    xpath: /nwFabricFeatureConfig
    add_children:
           - featureId: "{{ vxlan.featureId }}"
           - resourceConfig: 

- name: vxlan adding 1st subchildren to resourceConfig
  xml: 
    file: "{{ vxlanb_tmp }}"
    xpath: /nwFabricFeatureConfig/resourceConfig
    add_children: 
           - resourceId: "{{ compt_id }}"
           - configSpec: 
               class: "{{ vxlan.configspeca }}"

- name: vxlan adding 1st sub-sub-children to configspec
  xml:
    file: "{{ vxlanb_tmp }}"
    xpath: /nwFabricFeatureConfig/resourceConfig/configSpec
    add_children:
           - switch: 
           - vlanId: "{{ vxlan.vlid }}"
           - vmknicCount: "{{ vxlan.vmcnt }}"
           - ipPoolId: "{{ vxlan.ippoolid }}"

- name: vxlan adding 1st sub-sub-sub child to switch
  xml:
    file: "{{ vxlanb_tmp }}"
    xpath: /nwFabricFeatureConfig/resourceConfig/configSpec/switch
    add_children:
           - objectId: "{{ maindvs_id }}"

- name: vxlan adding 2nd parent resourceConfig
  xml:
    file: "{{ vxlanb_tmp }}"
    xpath: /nwFabricFeatureConfig
    add_children:
           - resourceConfig:

- name: vxlan adding 2nd subchildren to resourceConfig 
  xml: 
    file: "{{ vxlanb_tmp }}"
    xpath: /nwFabricFeatureConfig/resourceConfig
    add_children: 
           - resourceId: "{{ maindvs_id }}"
           - configSpec:
               class: "{{ vxlan.vdscon }}"

- name: vxlan adding 2nd sub-sub-children to configspec
  xml:
    file: "{{ vxlanb_tmp }}"
    xpath: /nwFabricFeatureConfig/resourceConfig/configSpec
    add_children:
           - switch: 
           - mtu: "{{ vxlan.mtu }}"
           - teaming: "{{ vxlan.team }}"

- name: vxlan adding 2nd sub-sub-sub child to switch
  xml:
    file: "{{ vxlanb_tmp }}"
    xpath: /nwFabricFeatureConfig/resourceConfig/configSpec/switch
    add_children:
           - objectId: "{{ maindvs_id }}"

- name: vxlan POST for Compt Cluster
  uri:
    url: "{{ nsx_inst_virt }}"
    method: POST
    user: "{{ nsx_user }}"
    password: "{{ nsx_password }}"
    body: "{{ lookup('file','/tmp/files/vxlan.xml') }}"
    force_basic_auth: yes
    HEADER_Content-Type: "{{ nsx_header }}"
  register: vxlan_status

- name: set fact for status
  set_fact:
    vxlan_stat: "{{ vxlan_status.status }}"

- name: failure message
  fail: msg="{{ vxlan_fail }}"
  when: vxlan_stat != "{{ success_status }}"

- name: remove file
  file: path="{{ vxlanb_tmp }}" state=absent
